app/clients/models.py
from app import db


class Client(db.Model):

    __tablename__ = 'clients_client'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    description = db.Column(db.Text())
    redirect_url = db.Column(db.Text())
    secret = db.Column(db.String(40), index=True)

    def __repr__(self):
        return '<Client %r>' % (self.name)

app/users/models.py
from app import db
from app.users import constants as USER

from app.clients.models import Client


clients = db.Table('clients',
    db.Column('client_id', db.Integer, db.ForeignKey('clients_client.id')),
    db.Column('user_id', db.Integer, db.ForeignKey('users_user.id')),
)

class User(db.Model):

    __tablename__ = 'users_user'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(120), unique=True, index=True)
    password = db.Column(db.String(120))
    role = db.Column(db.SmallInteger, default=USER.USER)
    clients = db.relationship('Client', secondary=clients,
                              backref=db.backref('users_user', lazy='dynamic'))


    def __init__(self, name=None, email=None, password=None):
        self.name = name
        self.email = email
        self.password = password

    def get_role(self):
        return USER.ROLE[self.role]

    def __repr__(self):
        return '<User %r>' % (self.name)

app/users/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email


class LoginForm(Form):
    email = TextField('Email', [Required(), Email()])
    password = PasswordField('Password', [Required()])

class RegisterForm(Form):

    name = TextField('Name', [Required()])
    email = TextField('Email', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    confirm = PasswordField('Repeat', [
        Required(),
        EqualTo('password', message='Passwords must match')
    ])
    accept_tos = BooleanField('Accept TOS', [Required()])

app/__init__.py
import os
import sys

from flask import Flask, render_template
from flask.ext.sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)

########################
# Configure Secret Key #
########################
def install_secret_key(app, filename='secret_key'):
    """Configure the SECRET_KEY from a file
    in the instance directory.

    If the file does not exist, print instructions
    to create it from a shell with a random key,
    then exit.
    """
    filename = os.path.join(app.instance_path, filename)

    try:
        app.config['SECRET_KEY'] = open(filename, 'rb').read()
    except IOError:
        print('Error: No secret key. Create it with:')
        full_path = os.path.dirname(filename)
        if not os.path.isdir(full_path):
            print('mkdir -p {filename}'.format(filename=full_path))
        print('head -c 24 /dev/urandom > {filename}'.format(filename=filename))
        sys.exit(1)

if not app.config['DEBUG']:
    install_secret_key(app)

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

from app.users.views import mod as usersModule
from app.auth.views import mod as authModule

app.register_blueprint(usersModule)
app.register_blueprint(authModule)

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from app import db
from app.users.forms import RegisterForm, LoginForm
from app.users.models import User
from app.users.decorators import requires_login


mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('/me/')
@requires_login
def home():
    return render_template('users/profile.html', user=g.user)


@mod.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.query.get(session['user_id'])


@mod.route('/login/', methods=['GET', 'POST'])
def login():

    form = LoginForm(request.form)

    if 'next' in request.args:
        print request.args['next']
        session['next'] = request.args['next']

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            session['user_id'] = user.id

            flash('Welcome %s' % user.name, 'success')
            next_page = session.get('next') or url_for('users.home')
            return redirect(next_page)

        flash('Wrong email or password', 'danger')

    return render_template("users/login.html", form=form)


@mod.route('/register/', methods=['GET', 'POST'])
def register():

    form = RegisterForm(request.form)

    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data)
        )
        db.session.add(user)
        db.session.commit()

        session['user_id'] = user.id

        flash('Thanks for registering', 'success')
        return redirect(url_for('users.home'))

    return render_template("users/register.html", form=form)

app/templates/base.html
<html>
  <head>
    <title>{% block title %}My Site{% endblock %}</title>
    {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock %}
    {% block css %} 

        <!-- Bootstrap -->
        <link rel="stylesheet" media="screen" href="/static/css/bootstrap.min.css">
        <link rel="stylesheet" media="screen" href="/static/css/bootstrap-theme.min.css">
        <!-- Bootstrap Admin Theme -->
        <link rel="stylesheet" media="screen" href="/static/css/bootstrap-admin-theme.css">
        <!-- Custom styles -->
        <style type="text/css">
            .alert{
                margin: 0 auto 20px;
            }
        </style>
    {% endblock %}
    {% block script %}
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
           <script type="text/javascript" src="/static/js/html5shiv.js"></script>
           <script type="text/javascript" src="/static/js/respond.min.js"></script>
        <![endif]-->
    {% endblock %}
  </head>
  <body class="bootstrap-admin-without-padding">
    <div id="header">{% block header %}{% endblock %}</div>
    <div id="messages-wrap">
      <div id="messages" class="">
        {% for category, msg in get_flashed_messages(with_categories=true) %}
          <div class="alert alert-{{ category }}">{{ msg }}</div>
        {% endfor %}
      </div>
    </div>
    <div id="container">{% block content %}{% endblock %}</div>
    <div id="footer">{% block footer %}{% endblock %}</div>
    {% block pagejs %}{% endblock %}
  </body>
</html>

app/templates/forms/macros.html
{% macro render_field(field, label=False) %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {% if field.errors %}
            {% for error in field.errors %}
                <label class="control-label" for="{{ field.id }}">{{ error|e }}</label>
            {% endfor %}
        {% endif %}
        {% if label %}
            {{ field.label }}
        {% endif %}
        {{ field(placeholder=field.label.text, **kwargs) }}
    </div>
{% endmacro %}

app/templates/users/login.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <div class="row">
      <div class="col-lg-12">
          <form method="post" action="." class="bootstrap-admin-login-form">
              {{ form.csrf_token }}
              <h1>Login</h1>
              {{ render_field(form.email, class="input text form-control") }}
              {{ render_field(form.password, class="input text form-control") }}
              <button class="btn btn-lg btn-primary" type="submit">Submit</button>
              <a href="{{ url_for('users.register') }}">Register</a>
          </form>
      </div>
  </div>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
  Hi {{ user.name }}!

<div class="col-md-10">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>Clients</h1>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="text-muted bootstrap-admin-box-title">My Clients</div>
                </div>
                <div class="bootstrap-admin-panel-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>id</th>
                                <th>Name</th>
                                <th>Secret</th>
                                <th>Redirect URL</th>
                                <th>Permissions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for client in user.clients %}
                            <tr>
                                <td>{{ client.id }}</td>
                                <td>{{ client.name }}</td>
                                <td>{{ client.secret }}</td>
                                <td>{{ client.redirect_url }}</td>
                                <td>All**</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    ** This is mock data
</div>
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}
{% block content %}
  {% from "forms/macros.html" import render_field %}
  <div class="row">
      <div class="col-lg-12">
        <form method="POST" action="." class="bootstrap-admin-login-form">
            {{ form.csrf_token }}
            {{ render_field(form.name, class="input text form-control") }}
            {{ render_field(form.email, class="input text form-control") }}
            {{ render_field(form.password, class="input text form-control") }}
            {{ render_field(form.confirm, class="input text form-control") }}
            {{ render_field(form.accept_tos, class="input checkbox form-control") }}
            {{ form.accept_tos.label.text }}
            <button class="btn btn-lg btn-primary" type="submit">Register</button>
            <a href="{{ url_for('users.login') }}">Login</a>
        </form>
    </div>
  </div>

{% endblock content %}